### ISSUE TITLE
Jobs failing on master

### ISSUE THREAD

**Issue by mackensen** [LafColITS/moodle-local_remote_courses#10]
Looks like a namespacing issue:

> Fatal error: Uncaught Error: Class "external_api" not found in /home/runner/work/moodle-local_remote_courses/moodle-local_remote_courses/moodle/local/remote_courses/externallib.php:36
> Stack trace:
> #0 /home/runner/work/moodle-local_remote_courses/moodle-local_remote_courses/moodle/local/remote_courses/tests/externallib_test.php(29): require_once()
> #1 /home/runner/work/moodle-local_remote_courses/moodle-local_remote_courses/moodle/vendor/phpunit/phpunit/src/Util/FileLoader.php(66): include_once('...')
> #2 /home/runner/work/moodle-local_remote_courses/moodle-local_remote_courses/moodle/vendor/phpunit/phpunit/src/Util/FileLoader.php(49): PHPUnit\Util\FileLoader::load()
> #3 /home/runner/work/moodle-local_remote_courses/moodle-local_remote_courses/moodle/vendor/phpunit/phpunit/src/Framework/TestSuite.php(395): PHPUnit\Util\FileLoader::checkAndLoad()
> #4 /home/runner/work/moodle-local_remote_courses/moodle-local_remote_courses/moodle/vendor/phpunit/phpunit/src/Framework/TestSuite.php(525): PHPUnit\Framework\TestSuite->addTestFile()
> #5 /home/runner/work/moodle-local_remote_courses/moodle-local_remote_courses/moodle/vendor/phpunit/phpunit/src/TextUI/TestSuiteMapper.php(67): PHPUnit\Framework\TestSuite->addTestFiles()
> #6 /home/runner/work/moodle-local_remote_courses/moodle-local_remote_courses/moodle/vendor/phpunit/phpunit/src/TextUI/Command.php(391): PHPUnit\TextUI\TestSuiteMapper->map()
> #7 /home/runner/work/moodle-local_remote_courses/moodle-local_remote_courses/moodle/vendor/phpunit/phpunit/src/TextUI/Command.php(112): PHPUnit\TextUI\Command->handleArguments()
> #8 /home/runner/work/moodle-local_remote_courses/moodle-local_remote_courses/moodle/vendor/phpunit/phpunit/src/TextUI/Command.php(97): PHPUnit\TextUI\Command->run()
> #9 /home/runner/work/moodle-local_remote_courses/moodle-local_remote_courses/moodle/vendor/phpunit/phpunit/phpunit(98): PHPUnit\TextUI\Command::main()
> #10 /home/runner/work/moodle-local_remote_courses/moodle-local_remote_courses/moodle/vendor/bin/phpunit(123): include('...')
> #11 {main}

**Comment by mackensen** [comment]
Result of https://tracker.moodle.org/browse/MDL-76583; the 4.2 release will have to break compatibility with previous releases.
